name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup test database
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: "postgresql://test:test@localhost:5432/test_db"
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run TypeScript check
      run: npx tsc --noEmit
    
    - name: Run linter
      run: npm run lint --if-present
      env:
        DATABASE_URL: "postgresql://test:test@localhost:5432/test_db"
        BETTER_AUTH_SECRET: "test-secret-key-32-chars-long-abcd" 
        BETTER_AUTH_URL: "http://localhost:3000"
    
    - name: Run tests
      run: npm test --if-present
      env:
        DATABASE_URL: "postgresql://test:test@localhost:5432/test_db"
        BETTER_AUTH_SECRET: "test-secret-key-32-chars-long-abcd" 
        BETTER_AUTH_URL: "http://localhost:3000"
  
# Deployment is handled by DigitalOcean auto-deploy (deploy_on_push: true in .do/app.yaml)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     
  #   - name: Deploy to DigitalOcean
  #     uses: digitalocean/app_action/deploy@v2
  #     with:
  #       token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}